app:
  name: identity-api
  namespace: cesi-eats
  image:
    repository: ghcr.io/cesi-eats/identity_api
    tag: latest

dependencies:
  lapinou:
    uri: amqp://rabbitmq-service.cesi-eats.svc.cluster.local:5672

  database:
    host: armanddebesse.fr
    port: 5432
    username: root
    password: password
    database_name: identity_db

jwt:
  secret: mysecret
  refresh_secret: myrefreshsecret
  expiration_minutes: 5
  refresh_expiration_days: 30
  kid: pKtzQAeUDbhtz2wZuY2ocX6gxJ3CTWkl