apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-app
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        app: {{ .Values.app.name }}-app
    spec:
      containers:
        - name: {{ .Values.app.name }}-container
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          imagePullPolicy: always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: {{ .Values.app.name }}-env-secret
          env:
            - name: TOKEN_EXPIRATION_MINUTES
              value: "{{ .Values.jwt.expiration_minutes }}"
            - name: REFRESH_TOKEN_EXPIRATION_DAYS
              value: "{{ .Values.jwt.refresh_expiration_days }}"
            - name: POSTGRES_PORT
              value: "{{ .Values.dependencies.database.port }}"