apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-app
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-app
    spec:
      containers:
        - name: {{ .Values.app.name }}-container
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: {{ .Values.app.name }}-env-secret
          env:
            - name: TOKEN_EXPIRATION_MINUTES
              value: {{ .Values.encoded_expiration_minutes }}
            - name: REFRESH_TOKEN_EXPIRATION_DAYS
              value: {{ .Values.encoded_refresh_expiration_days }}
            - name: DB_PORT
              value: {{ .Values.encoded_db_port }}