apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-env-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  LAPINOU_URI: {{ .Values.dependencies.lapinou.uri | b64enc | quote }}
  DB_HOST: {{ .Values.dependencies.database.host | b64enc | quote }}
  DB_USERNAME: {{ .Values.dependencies.database.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.dependencies.database.password | b64enc | quote }}
  DB_NAME: {{ .Values.dependencies.database.database_name | b64enc | quote }}
  SECRET_KEY: {{ .Values.jwt.secret | b64enc | quote }}
  REFRESH_SECRET_KEY: {{ .Values.jwt.refresh_secret | b64enc | quote }}
  KID: {{ .Values.jwt.kid | b64enc | quote }}
  TOKEN_EXPIRATION_MINUTES: {{ .Values.jwt.expiration_minutes | b64enc | quote }}
  REFRESH_TOKEN_EXPIRATION_DAYS: {{ .Values.jwt.refresh_expiration_days | b64enc | quote }}
  DB_PORT: {{ .Values.dependencies.database.port | b64enc | quote }}