apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-env-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
stringData:
    LAPINOU_URI: {{ .Values.dependencies.lapinou.uri }}
    DB_HOST: {{ .Values.dependencies.database.host }}
    DB_USERNAME: {{ .Values.dependencies.database.username }}
    DB_PASSWORD: {{ .Values.dependencies.database.password }}
    DB_NAME: {{ .Values.dependencies.database.database_name }}
    SECRET_KEY: {{ .Values.jwt.secret }}
    REFRESH_SECRET_KEY: {{ .Values.jwt.refresh_secret }}
    KID: {{ .Values.jwt.kid }}
    TOKEN_EXPIRATION_MINUTES: {{ .Values.encoded_expiration_minutes }}
    REFRESH_TOKEN_EXPIRATION_DAYS: {{ .Values.encoded_refresh_expiration_days }}
    DB_PORT: {{ .Values.encoded_db_port }}