apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-env-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
stringData:
  POSTGRES_HOST: {{ .Values.dependencies.database.host }}
  POSTGRES_USER: {{ .Values.dependencies.database.username }}
  POSTGRES_PASSWORD: {{ .Values.dependencies.database.password }}
  POSTGRES_DB: {{ .Values.dependencies.database.database_name }}
  SECRET_KEY: {{ .Values.jwt.secret }}
  REFRESH_SECRET_KEY: {{ .Values.jwt.refresh_secret }}
  KID: {{ .Values.jwt.kid }}