apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-env-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
stringData:
  LAPINOU_URI: {{ .Values.dependencies.lapinou.uri }}
  DB_HOST: {{ .Values.dependencies.database.host }}
  DB_USERNAME: {{ .Values.dependencies.database.username }}
  DB_PASSWORD: {{ .Values.dependencies.database.password }}
  DB_NAME: {{ .Values.dependencies.database.database_name }}
  SECRET_KEY: {{ .Values.jwt.secret }}
  REFRESH_SECRET_KEY: {{ .Values.jwt.refresh_secret }}
  KID: {{ .Values.jwt.kid }}
  TOKEN_EXPIRATION_MINUTES: {{ printf "%d" .Values.jwt.expiration_minutes | b64enc | quote }}
  REFRESH_TOKEN_EXPIRATION_DAYS: {{ printf "%d" .Values.jwt.refresh_expiration_days | b64enc | quote }}
  DB_PORT: {{ printf "%d" .Values.dependencies.database.port | b64enc | quote }}